extends: default

rules:
  line-length:
    max: 120
  indentation:
    spaces: 2
  truthy:
    allowed-values: ["true", "false", "on"]
  comments:
    min-spaces-from-content: 1
  document-start: disable
  document-end: disable
