---
name: Code Quality Checks

"on":
  push:
  pull_request:
    branches: [main]

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  code-quality-gate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          # Fetch full history for SonarQube analysis
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements-test.txt
          pip install flake8 pylint bandit pydocstyle lizard black mypy
          pip install pytest yamllint

      - name: Generate reports for SonarQube
        run: |
          # Create reports directory
          mkdir -p reports

          # CRITICAL: Unit tests with coverage - MUST pass
          pytest tests/ \
            --cov=projects/can_data_platform/scripts \
            --cov=projects/can_data_platform/src \
            --cov=.github/issue_deployment \
            --cov-report=term-missing \
            --cov-report=html \
            --cov-report=xml:coverage.xml \
            --cov-report=json:coverage.json \
            --cov-fail-under=95 \
            --junit-xml=test-results.xml

          # NON-CRITICAL: Pylint with output for SonarQube - can fail
          pylint projects/can_data_platform/scripts/ \
                 projects/can_data_platform/src/ \
                 .github/issue_deployment/ \
                 tests/ \
                 --output-format=text \
                 --reports=no \
                 --score=no > reports/pylint-report.txt || \
                 echo "⚠️ Pylint issues found - check reports"

          # NON-CRITICAL: Bandit security scan - can fail
          bandit -r projects/can_data_platform/scripts/ \
                    projects/can_data_platform/src/ \
                    .github/issue_deployment/ \
                    tests/ \
                 --skip B101,B311 \
                 --format json \
                 --output bandit-report.json || \
                 echo "⚠️ Security issues found - check reports"

          # NON-CRITICAL: Flake8 style check - can fail
          flake8 projects/can_data_platform/scripts/ \
                 projects/can_data_platform/src/ \
                 .github/issue_deployment/ \
                 tests/ \
                 --output-file=reports/flake8-report.txt || \
                 echo "⚠️ Style issues found - check reports"

      - name: Critical YAML validation
        # CRITICAL: Workflow files must be valid - MUST pass
        run: |
          yamllint .github/workflows/*.yml

      - name: SonarQube Scan
        # Run SonarQube scan on all branches
        # (try first, fallback if free tier restricts)
        uses: sonarsource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        continue-on-error: true

      - name: SonarQube Quality Gate Check
        # Only run quality gate check if scan succeeded and report file exists
        if: hashFiles('.scannerwork/report-task.txt') != ''
        uses: SonarSource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          scanMetadataReportFile: .scannerwork/report-task.txt
        continue-on-error: true

      - name: Custom Quality Gate Analysis
        # Always run our own quality checks to analyze the generated reports
        run: |
          echo "=============================================="
          echo "📊 Quality Gate Analysis"
          echo "=============================================="
          echo "🔍 Analyzing generated reports..."

          # CRITICAL: Run comprehensive quality checks - MUST pass
          python run_quality_checks.py

          echo "=============================================="
          if [ -f ".scannerwork/report-task.txt" ]; then
            echo "✅ SonarQube scan completed - check dashboard for" \
                 "detailed analysis"
          else
            echo "ℹ️ SonarQube scan not available (free tier limitation" \
                 "or configuration issue)"
          fi
          echo "📊 Local quality reports generated and uploaded as" \
               "artifacts"
          echo "=============================================="

      - name: Upload quality check artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: code-quality-artifacts
          path: |
            quality_checks.log
            htmlcov/
            coverage.xml
            coverage.json
            test-results.xml
            bandit-report.json
            reports/
            .scannerwork/
